# action.yml
name: 'Update Version Badge'
description: 'Updates the version number in an SVG badge'

inputs:
  new_version:
    required: true
    description: 'New version number to update in badge'
  badge_path:
    required: true
    description: 'Path to the SVG badge file'
  commit_message:
    required: false
    description: 'Custom commit message'
    default: 'Update version badge'

runs:
  using: 'composite'
  steps:
    - name: Update version badge
      shell: bash
      run: |
        # Extract new version
        NEW_VERSION="${{ inputs.new_version }}"
        
        # Update SVG version text with sed
        sed -i 's/<!-- VERSION_PLACEHOLDER -->.*<!-- VERSION_PLACEHOLDER -->/<!-- VERSION_PLACEHOLDER -->'$NEW_VERSION'<!-- VERSION_PLACEHOLDER -->/g' "${{ inputs.badge_path }}"
        
        # Commit changes
        git add "${{ inputs.badge_path }}"
        git commit -m "${{ inputs.commit_message }} to $NEW_VERSION" || echo "No changes to commit"
        git push origin HEAD:${GITHUB_REF#refs/heads/}