name: Build Project Jar

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project to build (projectA or projectB)"
        required: true
        default: "projectA"
        type: choice
        options:
        - projectA
        - projectB
      release_option:
        description: "Choose action: 'Release' to save JAR for later use, 'None' for only build and test"
        required: true
        default: "None"
        type: choice
        options:
          - Release
          - None

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21 # Adjust to your Java version
          distribution: 'temurin'

      # Validate project_name input
      - name: Validate Project Input
        run: |
          if [ "${{ github.event.inputs.project_name }}" != "projectA" ] && [ "${{ github.event.inputs.project_name }}" != "projectB" ]; then
            echo "Invalid project name: ${{ github.event.inputs.project_name }}"
            echo "Please select either 'projectA' or 'projectB'."
            exit 1
          fi

      # Build and Test the selected project
      - name: Build and Test Project
        run: |
          cd ${{ github.event.inputs.project_name }}
          mvn clean package test

      # Create a Release (only if Release option is chosen)
      - name: Create GitHub Release
        if: ${{ github.event.inputs.release_option == 'Release' }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.project_name }}-v1.0
          release_name: ${{ github.event.inputs.project_name }} Release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload JAR to Release
      - name: Upload JAR to Release
        if: ${{ github.event.inputs.release_option == 'Release' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.inputs.project_name }}/target/*.jar
          asset_name: ${{ github.event.inputs.project_name }}.jar
          asset_content_type: application/java-archive
