name: Build and Publish maven package

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project to build (projectA or projectB)"
        required: true
        default: "projectA"
        type: choice
        options:
        - projectA
        - projectB
      release_option:
        description: "Choose Action"
        required: true
        default: "NONE"
        type: choice
        options:
          - RELEASE
          - DRY_RUN
          - NONE

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21 # Adjust to your Java version
          distribution: 'temurin'
          cache: maven

      # Validate project_name input
      - name: Validate Project Input
        run: |
          if [ "${{ github.event.inputs.project_name }}" != "projectA" ] && [ "${{ github.event.inputs.project_name }}" != "projectB" ]; then
            echo "Invalid project name: ${{ github.event.inputs.project_name }}"
            echo "Please select either 'projectA' or 'projectB'."
            exit 1
          fi

      # Build and Test the selected project
      - name: Build and Test Project
        run: |
          cd ${{ github.event.inputs.project_name }}
          mvn -f pom.xml clean --also-make-dependents install
      
      # Release jar
      - name: Conditional Release
        if: ${{ github.event.inputs.release_option == 'RELEASE' }}
        run: echo "Releasing the built JAR file"

      # Upload the JAR as an artifact if release_option is 'Release'
      - name: Upload JAR file
        if: ${{ github.event.inputs.release_option == 'Release' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.project_name }}-jar
          path: ${{ github.event.inputs.project_name }}/target/*.jar
      
