name: Build and Publish maven package

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project to build (projectA or projectB)"
        required: true
        default: "projectA"
        type: choice
        options:
        - projectA
        - projectB
      release_option:
        description: "Choose Action"
        required: true
        default: "NONE"
        type: choice
        options:
          - RELEASE
          - DRY_RUN
          - NONE

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21 # Adjust to your Java version
          distribution: 'temurin'
          cache: maven

      # Configure Git for GITHUB_TOKEN
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      
      
      # Authenticate with GitHub Packages in workflow:
      - name: Authenticate with GitHub Packages
        run: |
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.GITHUB_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
      
                
      # Perform Maven Release if Release option is selected
      - name: Perform Maven Release
        if: ${{ github.event.inputs.release_option == 'RELEASE' }}
        run: |
          cd ${{ github.event.inputs.project_name }}
          mvn release:clean release:prepare release:perform -B


      # Build and Test the selected project
      - name: Build and Test Project
        if: ${{ github.event.inputs.release_option == 'NONE' }}
        run: |
          cd ${{ github.event.inputs.project_name }}
          mvn -f pom.xml clean --also-make-dependents install
      

      # Upload the JAR as an artifact if release_option is 'Release'
      - name: Upload JAR file
        if: ${{ github.event.inputs.release_option == 'RELEASE' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.project_name }}-jar
          path: ${{ github.event.inputs.project_name }}/target/*.jar
      
